baseURL = "https://scriabinclub.com/"
languageCode = "en"
title = "Scriabin Club"
DefaultContentLanguage = "en"
theme = "tigers"
enableRobotsTXT = true
paginate = 30

[taxonomies]
  cat = 'cat'

[markup.goldmark.renderer]
  # Allow HTML in Markdown
unsafe = true

[params]
###########################
## GLOBAL VARS (default) ##
###########################

###########################
###### LOOK AND FEEL ######
###########################

featuredImage = "/images/banner.jpg"
# if no bg image set, or cannot be loaded, will fallback on bgColor
bgImage = "/images/bg.svg"
bgColor = "#202430" #original bg color, average of bg.jpg: #6e78a2
logo = "/logo.svg"


#######################
### LOCALIZATION (DEFAULT) ######
#######################

sitename = "Scriabin Club"
strNextPage = "Next page→"
strPreviousPage = "← Previous page"
strLinkDescriptor = "Link to the homepage of Scriabin Club."

[languages]

[languages.en] 
languageName = "English"
weight = 1
#[languages.en.menu]
#[[languages.en.menu.main]]
#name = "Home"
#title = "Home"
#url = "/"
#weight = 0

###################
### ZEE GERMANS ###
###################

[languages.de] 
languageName = "Deutsch"
weight = 2

[languages.de.params]
## possible param overwrites (for localization) go here
sitename = "Skrjabin Klub"
strNextPage = "Nächste Seite→"
strPreviousPage = "← Vorige Seite"
strLinkDescriptor = "Link zur Homepage des Skrjabin Klubs."

###################
### NEDERLANDS ####
###################
[languages.nl] 
languageName = "Nederlands"

[languages.nl.params]
sitename = "Scriabin Club"
strNextPage = "Terug →"
strPreviousPage = "← Vooruit"
strLinkDescriptor = "Link naar de Hoofdpagina van de Scriabin Club."

###################
### RUSSIAN ####
###################

[languages.ru] 
languageName = "Русский"

[languages.ru.params]

sitename = "Скрябинский Клуб"
strNextPage = "Следующая страница →"
strPreviousPage = "← Предыдущая страница"
strLinkDescriptor = "Ссылка на домашнюю страницу Скрябинского Клуба."
